# gui/models/board_state.py

import chess
from typing import List, Optional
from .move import Move

class BoardState:
    def __init__(self, fen: Optional[str] = None):
        """
        Initializes a BoardState wrapper around a chess.Board.
        
        Args:
            fen: Starting FEN string. If None, initializes standard starting position.
        """
        if fen:
            self._board = chess.Board(fen)
        else:
            self._board = chess.Board()
        # Holds the up-to-date legal moves parsed from our C++ Chess Engine
        self.cached_engine_legal_moves: List[str] = []

    @staticmethod
    def _convert_square(idx: int) -> int:
        """
        Converts between C++ engine indexing (0 = A8, 63 = H1)
        and python-chess indexing (0 = A1, 63 = H8).
        
        This mapping is self-inverse.
        """
        return (7 - (idx // 8)) * 8 + (idx % 8)

    @staticmethod
    def index_to_coordinate(idx: int) -> str:
        """
        Converts a C++ square index (0 = A8, 63 = H1) to algebraic coordinates (e.g. "e2").
        """
        files = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
        col = idx % 8
        row = 8 - (idx // 8)
        return f"{files[col]}{row}"

    @staticmethod
    def coordinate_to_index(coord: str) -> int:
        """
        Converts algebraic coordinates (e.g. "e2") to a C++ square index (0 = A8, 63 = H1).
        """
        col = ord(coord[0]) - ord('a')
        row = 8 - int(coord[1])
        return row * 8 + col

    def piece_at(self, cpp_idx: int) -> str:
        """
        Returns the piece character at the given C++ index ('P', 'n', etc.),
        or '.' if the square is empty.
        """
        pc_idx = self._convert_square(cpp_idx)
        piece = self._board.piece_at(pc_idx)
        if piece is None:
            return '.'
        return piece.symbol()

    def get_legal_moves(self, from_cpp_idx: int) -> List[int]:
        """
        Returns a list of legal destination C++ indices for a piece on `from_cpp_idx`
        using the cached list of moves generated by our C++ Chess Engine.
        """
        from_coord = self.index_to_coordinate(from_cpp_idx)
        legal_destinations = []
        
        for move_str in self.cached_engine_legal_moves:
            if move_str.startswith(from_coord) and len(move_str) >= 4:
                to_coord = move_str[2:4]
                legal_destinations.append(self.coordinate_to_index(to_coord))
                
        return legal_destinations

    def is_legal(self, move: Move) -> bool:
        """
        Checks if a given Move is legal in the current position using the C++ engine's cached moves.
        """
        from_coord = self.index_to_coordinate(move.from_square)
        to_coord = self.index_to_coordinate(move.to_square)
        candidate = from_coord + to_coord
        
        for move_str in self.cached_engine_legal_moves:
            if move_str.startswith(candidate):
                return True
        return False

    def make_move(self, move: Move) -> Optional[str]:
        """
        Attempts to execute the move on the board.
        Returns the SAN move string if successful, None if the move was illegal.
        """
        from_pc = self._convert_square(move.from_square)
        to_pc = self._convert_square(move.to_square)
        
        piece = self._board.piece_at(from_pc)

        if piece is None:
            return None

        # Determine if this move is a pawn promotion
        is_pawn = piece and piece.piece_type == chess.PAWN
        target_rank = chess.square_rank(to_pc)
        is_promotion_rank = (target_rank == 7 and piece.color == chess.WHITE) or \
                             (target_rank == 0 and piece.color == chess.BLACK)
        
        promotion_type = None
        if is_pawn and is_promotion_rank:
            # Default to Queen if not specified
            prom_char = move.promotion.lower() if move.promotion else 'q'
            prom_map = {'q': chess.QUEEN, 'r': chess.ROOK, 'b': chess.BISHOP, 'n': chess.KNIGHT}
            promotion_type = prom_map.get(prom_char, chess.QUEEN)
            
        pc_move = chess.Move(from_pc, to_pc, promotion=promotion_type)
        
        # Verify legality using the C++ engine cached moves
        from_coord = self.index_to_coordinate(move.from_square)
        to_coord = self.index_to_coordinate(move.to_square)
        candidate = from_coord + to_coord
        if is_pawn and is_promotion_rank:
            prom_char = move.promotion.lower() if move.promotion else 'q'
            candidate += prom_char
            
        if candidate in self.cached_engine_legal_moves:
            # Generate the algebraic notation (SAN) *before* pushing to board state
            san_string = self._board.san(pc_move)
            self._board.push(pc_move)
            return san_string
        return None

    def is_check(self) -> bool:
        """Returns True if the side to move is in check."""
        return self._board.is_check()

    def get_fen(self) -> str:
        """Returns the current board position as a FEN string."""
        return self._board.fen()

    def set_fen(self, fen: str):
        """Sets the board to the position described by the FEN string."""
        self._board.set_fen(fen)

    @property
    def turn(self) -> bool:
        """Returns True if it is White's turn, False for Black."""
        return self._board.turn

    def undo_last_move(self) -> Optional[chess.Move]:
        """
        Pops the last executed move from the stack and restores the board state.
        Returns the popped chess.Move, or None if the stack was empty.
        """
        if len(self._board.move_stack) > 0:
            return self._board.pop()
        return None

    def get_board_state_array(self) -> List[List[str]]:
        """
        Returns a 2D 8x8 list grid representation matching the legacy START_POS representation.
        Index [row][col] matches C++ indexing coordinates (Row 0 = A8-H8).
        """
        grid = []
        for r in range(8):
            row = []
            for f in range(8):
                cpp_idx = r * 8 + f
                row.append(self.piece_at(cpp_idx))
            grid.append(row)
        return grid
